#https://github.com/spring-cloud/spring-cloud-netflix/issues/1820
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
    inetutils:
      preferred-networks:
        - 10.0
  profiles:
     active: native
  application:
    name: config-server
server:
  port: 7766
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      currentDefaultZone: http://eureka-server:7777/eureka/
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${eureka.client.serviceUrl.currentDefaultZone}}
logging:
  path: /applog
  file: "${logging.path}/${spring.application.name}.log"