spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  application:
    name: config-server

server:
  port: 7766

eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-server:7777/eureka/