#######################
## 所有服务共享配置文件 ##
#######################

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/

#Zipkin服务地址
spring:
  zipkin:
    base-url: http://localhost:7755
  sleuth:
    sampler:
      percentage: 1.0

#关闭Actuator API接口安全验证
management:
  security:
    enabled: false

#开启Feign熔断器功能
feign:
  hystrix:
    enabled: true

endpoints:
  health:
    sensitive: false
    enabled: true
  actuator:
    enabled: true
    sensitive: false
  beans:
    sensitive: false
    enabled: true