zuul:
  routes:
    hiapi:
      path: /app-sample-consume/**
      serviceId: app-sample-consume

    ribbonapi:
      path: /app-sample-produce/**
      serviceId: app-sample-produce

  prefix: /api

# 网关API访问示例  http://localhost:7000/api/app-sample-consume/hi?name=wangyongtao
