version: '3'
services:
  app-storage-qiniu:
    image: wangyt/app-storage-qiniu:${APP_IMAGE_VER}
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.labels.region == Blue
    ports:
      - 9400:9400
    environment:
      - FILEBEAT_OP_LS_HOSTS=${FILEBEAT_OP_LS_HOSTS}
      - CLUSTERS_EUREKA_SERVER_URLS=${CLUSTERS_EUREKA_SERVER_URLS}
    entrypoint:
      - ./wait-for-it.sh
      - config-server:7766
      - --timeout=0
      - --strict
      - --
      - /filebeat-springboot-entrypoint.sh
      - /app-storage-qiniu.jar
      - --spring.profiles.active=${SPRING_PROFILES_ACTIVE}
networks:
  default:
    external:
      name: cloud-cook-overlay