version: '3'
services:
  eureka-server:
    image: wangyt/eureka-server:${INFRA_IMAGE_VER}
    deploy:
      placement:
        constraints: [node.labels.name == dlink-ops-03-backend-204]
    environment:
      - FILEBEAT_OP_LS_HOSTS=${FILEBEAT_OP_LS_HOSTS}
      - CLUSTERS_EUREKA_SERVER_MODE=true
      - CLUSTERS_EUREKA_SERVER_PORT=7777
      - CLUSTERS_EUREKA_SERVER_INSTANCE_HOSTNAME=eureka-server
      - CLUSTERS_EUREKA_SERVER_URLS=${CLUSTERS_EUREKA_SERVER_URLS}
    entrypoint:
      - ./filebeat-springboot-entrypoint.sh
      - /eureka-server.jar
      - --spring.profiles.active=${SPRING_PROFILES_ACTIVE}
    ports:
      - 7777:7777
  eureka-server-2:
    image: wangyt/eureka-server:${INFRA_IMAGE_VER}
    deploy:
      placement:
        constraints: [node.labels.name == dlink-ops-06-backend-205]
    environment:
      - FILEBEAT_OP_LS_HOSTS=${FILEBEAT_OP_LS_HOSTS}
      - CLUSTERS_EUREKA_SERVER_MODE=true
      - CLUSTERS_EUREKA_SERVER_PORT=7777
      - CLUSTERS_EUREKA_SERVER_INSTANCE_HOSTNAME=eureka-server-2
      - CLUSTERS_EUREKA_SERVER_URLS=${CLUSTERS_EUREKA_SERVER_URLS}
    entrypoint:
      - ./filebeat-springboot-entrypoint.sh
      - /eureka-server.jar
      - --spring.profiles.active=${SPRING_PROFILES_ACTIVE}
    ports:
      - 7777:7777
  config-server:
    image: wangyt/config-server:${INFRA_IMAGE_VER}
    deploy:
      placement:
        constraints: [node.labels.name == dlink-ops-03-backend-204]
    depends_on:
      - eureka-server
    environment:
      - FILEBEAT_OP_LS_HOSTS=${FILEBEAT_OP_LS_HOSTS}
      - CLUSTERS_EUREKA_SERVER_URLS=${CLUSTERS_EUREKA_SERVER_URLS}
    entrypoint:
      - ./wait-for-it.sh
      - eureka-server:7777
      - --timeout=0
      - --strict
      - --
      - /filebeat-springboot-entrypoint.sh
      - /config-server.jar
      - --spring.profiles.active=native
    ports:
      - 7766:7766
  gateway-service:
    image: wangyt/gateway-service:${INFRA_IMAGE_VER}
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.labels.region == Blue
    depends_on:
      - eureka-server
      - config-server
    environment:
      - FILEBEAT_OP_LS_HOSTS=${FILEBEAT_OP_LS_HOSTS}
      - CLUSTERS_EUREKA_SERVER_URLS=${CLUSTERS_EUREKA_SERVER_URLS}
    entrypoint:
      - ./wait-for-it.sh
      - config-server:7766
      - --timeout=0
      - --strict
      - --
      - /filebeat-springboot-entrypoint.sh
      - /gateway-service.jar
      - --spring.profiles.active=${SPRING_PROFILES_ACTIVE}
    ports:
      - 7000:7000
networks:
  default:
    external:
      name: cloud-cook-overlay