# 需要事先创建网络 docker network create cloud-cook
# docker network ls

version: '3'
services:
  app-sample-consume:
    image: wangyt/app-sample-consume:${IMAGE_VER}
    deploy:
      resources:
        limits:
          memory: 999M
    depends_on:
      - eureka-server
      - config-server
    ports:
      - 9500:9500
    env_file: .env
    entrypoint:
      - ./wait-for-it.sh
      - config-server:7766
      - --timeout=0
      - --strict
      - --
      - /filebeat-springboot-entrypoint.sh
      - /app-sample-consume.jar
      - --spring.profiles.active=${SPRING_PROFILES_ACTIVE}

networks:
  default:
    external:
      name: cloud-cook