spring:
  application:
    name: eureka-server
  ## 单机模式
  profiles: default
server:
  port: 7777
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
## 集群模式
---
spring:
  profiles: eureka-server
  application:
    name: eureka-server
server:
  port: 7777
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://eureka-server2:7778/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
---
spring:
  profiles: eureka-server2
  application:
    name: eureka-server
server:
  port: 7778
eureka:
  instance:
    hostname: eureka-server2
  client:
    serviceUrl:
      defaultZone: http://eureka-server:7777/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000